environment:
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - git version
  - npm test
matrix:
  fast_finish: true
